### ISSUE TITLE
Pipeline Cost?

### ISSUE THREAD

**Issue by startswithaj** [nicolai86/awesome-codepipeline-ci#2]
Hey @nicolai86 with this approach do you get charged $1 per pipeline? Or because your bringing them down before the 30 day window, you don't get charged?

**Comment by nicolai86** [comment]
As far as I know AWS doesn't charge for active pipelines that live less than 30 days, so the only pipeline that should generate AWS CodePipeline charges is your template.

But remember that the other components involved cost too: AWS Lambda, AWS CodeBuild...
