### ISSUE TITLE
Open Source license to this project

### ISSUE THREAD

**Issue by obscurerichard** [nicolai86/awesome-codepipeline-ci#4]
Would you consider adding a license file to this project? This would be consistent with good [community practices](http://wiki.opensource.org/bin/Projects/How+to+apply+an+open+source+license+to+your+project) and would allow others to build upon your work with a clear set of rules for what is acceptable.

For maximum compatibility with other free software projects, please consider using MIT license, such as expressed here:

https://opensource.org/licenses/MIT

(replace the copyright statement with your copyright, of course)

**Comment by nicolai86** [comment]
@obscurerichard thanks for bringing this topic up! I’ll add a license to this project soon.

**Comment by nicolai86** [comment]
fixed with https://github.com/nicolai86/awesome-codepipeline-ci/commit/25440efde3f3b13c61019e6f8909c9362202edf6

**Comment by obscurerichard** [comment]
Thank you! @nicolai86 !
